all:
	$(MAKE) -C ./squashfs-2.2-r2-7z
	$(MAKE) -C ./squashfs-3.0-e2100
	$(MAKE) -C ./squashfs-3.2-r2
	$(MAKE) -C ./squashfs-3.2-r2-lzma
	$(MAKE) -C ./squashfs-3.2-r2-hg612-lzma
	$(MAKE) -C ./squashfs-3.2-r2-wnr1000
	$(MAKE) -C ./squashfs-3.2-r2-rtn12
	$(MAKE) -C ./squashfs-3.3
	$(MAKE) -C ./squashfs-3.3-lzma
	$(MAKE) -C ./squashfs-3.3-grml-lzma
	$(MAKE) -C ./squashfs-3.4-cisco
	$(MAKE) -C ./squashfs-3.4-nb4
	$(MAKE) -C ./squashfs-4.0-lzma
	$(MAKE) -C ./squashfs-4.0-realtek
	$(MAKE) -C ./squashfs-2.0-nb4
	$(MAKE) -C ./squashfs-4.2
	$(MAKE) -C ./squashfs-4.2-official

clean:
	$(MAKE) -C ./squashfs-2.2-r2-7z clean
	$(MAKE) -C ./squashfs-3.0-e2100 clean
	$(MAKE) -C ./squashfs-3.2-r2 clean
	$(MAKE) -C ./squashfs-3.2-r2-lzma clean
	$(MAKE) -C ./squashfs-3.2-r2-hg612-lzma clean
	$(MAKE) -C ./squashfs-3.2-r2-wnr1000 clean
	$(MAKE) -C ./squashfs-3.2-r2-rtn12 clean
	$(MAKE) -C ./squashfs-3.3 clean
	$(MAKE) -C ./squashfs-3.3-lzma clean
	$(MAKE) -C ./squashfs-3.3-grml-lzma clean
	$(MAKE) -C ./squashfs-3.4-cisco clean
	$(MAKE) -C ./squashfs-3.4-nb4 clean
	$(MAKE) -C ./squashfs-4.0-lzma clean
	$(MAKE) -C ./squashfs-4.0-realtek clean
	$(MAKE) -C ./squashfs-2.0-nb4 clean
	$(MAKE) -C ./squashfs-4.2 clean
	$(MAKE) -C ./squashfs-4.2-official clean
