PROG = lzmadec
CC = gcc 
LIB = 
RM = rm -f
CFLAGS = -c -O2 -Wall -pedantic -D _LZMA_PROB32 

OBJS = LzmaTest.o LzmaDecode.o 

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) -o $(PROG) $(LDFLAGS) $(OBJS) $(LIB)

LzmaTest.o: LzmaTest.c
	$(CC) $(CFLAGS) LzmaTest.c

LzmaDecode.o: LzmaDecode.c
	$(CC) $(CFLAGS) LzmaDecode.c


clean:
	-$(RM) $(PROG) $(OBJS)

